apiVersion: v1
kind: ConfigMap
metadata:
  name: xgoods-ui-signup-config
  namespace: xgoods
  labels:
    app: signup
    env: development
data:
  APP_ENV: "development"
  BACKEND_URL: "http://backend-service:8080"
