apiVersion: v1
kind: ConfigMap
metadata:
  name: xgoods-backend-signup-config
  namespace: xgoods
  labels:
    name: xgoods
    app: signup
    env: development
    ver: "1.0"
    component: xgoods-backend-signup
data:
  # The frontend talks to this backend service
  FLASK_APP: "app.py"
  FLASK_ENV: "development"
  # Backend talks to the database service (we will name the DB service 'xgoods-db-signup')
  DB_HOST: "xgoods-db-signup"
  DB_NAME: "userdb"
  DB_USER: "root"
